apiVersion: v1
kind: Pod
metadata:
  name: pod-tolerate-all
  labels:
    app: test-scheduling
    workload: system
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
  tolerations:
  # Tolère TOUS les taints (y compris ceux du master)
  - operator: "Exists"
  restartPolicy: Always
